# Generated by Django 5.1.15 on 2026-08-30 10:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctorcredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorcredential",
            name="file",
            field=models.FileField(
                storage=accounts.models.private_media_storage,
                upload_to="credentials/",
                verbose_name="مستند الإثبات",
            ),
        ),
    ]
