# Generated by Django 5.1.15 on 2026-08-30 12:02

import accounts.models
import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_move_credentials_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="proof_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="رابط إثبات (اختياري)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "بانتظار المراجعة"),
                    ("APPROVED", "معتمد"),
                    ("REJECTED", "مرفوض"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="حالة المراجعة",
            ),
        ),
        migrations.AlterField(
            model_name="doctorcredential",
            name="file",
            field=models.FileField(
                storage=accounts.models.private_media_storage,
                upload_to="credentials/",
                validators=[
                    config.validators.FileSizeValidator(5),
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "pdf"]
                    ),
                ],
                verbose_name="مستند الإثبات",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="doctors/",
                validators=[
                    config.validators.FileSizeValidator(3),
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif"]
                    ),
                ],
                verbose_name="الصورة",
            ),
        ),
    ]
