# Generated by Django 5.1.15 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_backfill_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="facebook",
            field=models.URLField(blank=True, max_length=300, verbose_name="فيسبوك"),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="instagram",
            field=models.URLField(blank=True, max_length=300, verbose_name="إنستغرام"),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="linkedin",
            field=models.URLField(blank=True, max_length=300, verbose_name="لينكدإن"),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="twitter",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="إكس (تويتر)"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="website",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="الموقع الشخصي"
            ),
        ),
    ]
