# Generated by Django 5.1.15 on 2026-08-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_doctorprofile_facebook_doctorprofile_instagram_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="website",
        ),
    ]
