# Generated by Django 5.1.15 on 2026-08-21 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "role_ar",
                    models.CharField(max_length=120, verbose_name="المنصب (عربي)"),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="المنصب (إنجليزي)"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="board/", verbose_name="الصورة"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر")),
            ],
            options={
                "verbose_name": "عضو مجلس إدارة",
                "verbose_name_plural": "مجلس الإدارة",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                ("email", models.EmailField(max_length=254, verbose_name="البريد")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("TOPIC", "موضوع"), ("FAQ", "سؤال شائع")],
                        default="TOPIC",
                        max_length=6,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=250, verbose_name="العنوان (عربي)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                (
                    "body_ar",
                    models.TextField(blank=True, verbose_name="المحتوى (عربي)"),
                ),
                (
                    "body_en",
                    models.TextField(blank=True, verbose_name="المحتوى (إنجليزي)"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="مفتاح أيقونة تعرضه الواجهة",
                        max_length=40,
                        verbose_name="أيقونة (مفتاح)",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="رابط فيديو")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر")),
            ],
            options={
                "verbose_name": "موضوع توعية",
                "verbose_name_plural": "بوابة توعية المرضى",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=250, verbose_name="العنوان (عربي)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="الوصف (عربي)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="الوصف (إنجليزي)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONFERENCE", "مؤتمر"),
                            ("WORKSHOP", "ورشة"),
                            ("SEMINAR", "ندوة"),
                        ],
                        default="CONFERENCE",
                        max_length=12,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="التاريخ"),
                ),
                (
                    "location_ar",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="المكان (عربي)"
                    ),
                ),
                (
                    "location_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="المكان (إنجليزي)"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="رابط فيديو")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشاط",
                "verbose_name_plural": "الأنشطة والمؤتمرات",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="العنوان (عربي)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="activities/files/", verbose_name="الملف"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="content.activity",
                        verbose_name="النشاط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف نشاط",
                "verbose_name_plural": "ملفات الأنشطة",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=250, verbose_name="العنوان (عربي)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                ("body_ar", models.TextField(blank=True, verbose_name="النص (عربي)")),
                (
                    "body_en",
                    models.TextField(blank=True, verbose_name="النص (إنجليزي)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="صورة"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="news/files/",
                        verbose_name="مرفق",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشور"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="موعد النشر"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "الأخبار والإعلانات",
                "ordering": ["-publish_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=250, verbose_name="النص (عربي)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="النص (إنجليزي)"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="رابط (اختياري)"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, verbose_name="مثبّت أعلى الموقع"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مُفعّل")),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="يبدأ في"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعلان ذكي",
                "verbose_name_plural": "الإعلانات الذكية",
                "ordering": ["-is_pinned", "-starts_at"],
            },
        ),
    ]
