# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patienttopic",
            name="summary_ar",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="مختصر (عربي)"
            ),
        ),
        migrations.AddField(
            model_name="patienttopic",
            name="summary_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="مختصر (إنجليزي)"
            ),
        ),
    ]
