# Generated by Django 5.1.15 on 2026-08-30 12:02

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_patienttopic_summary_ar_patienttopic_summary_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="activities/",
                validators=[
                    config.validators.FileSizeValidator(5),
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif"]
                    ),
                ],
                verbose_name="صورة الغلاف",
            ),
        ),
        migrations.AlterField(
            model_name="activityfile",
            name="file",
            field=models.FileField(
                upload_to="activities/files/",
                validators=[
                    config.validators.FileSizeValidator(20),
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx", "ppt", "pptx"]
                    ),
                ],
                verbose_name="الملف",
            ),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="board/",
                validators=[
                    config.validators.FileSizeValidator(3),
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif"]
                    ),
                ],
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="news/files/",
                validators=[
                    config.validators.FileSizeValidator(20),
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx", "ppt", "pptx"]
                    ),
                ],
                verbose_name="مرفق",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/",
                validators=[
                    config.validators.FileSizeValidator(5),
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif"]
                    ),
                ],
                verbose_name="صورة",
            ),
        ),
    ]
