# Generated by Django 5.1.15 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_activity_cover_image_alter_activityfile_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=60, verbose_name="الهاتف"),
                ),
                (
                    "address_ar",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="العنوان (عربي)"
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                (
                    "map_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="رابط الخريطة"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, max_length=300, verbose_name="فيسبوك"),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="إكس (تويتر)"
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="إنستغرام"
                    ),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, max_length=300, verbose_name="يوتيوب"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, max_length=300, verbose_name="لينكدإن"),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="تيليغرام"
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(blank=True, max_length=300, verbose_name="واتساب"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
    ]
