# Generated by Django 5.1.15 on 2026-08-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_sitesettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
