# Generated by Django 5.1.15 on 2026-10-05 22:30

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_sitesettings_require_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityfile",
            name="file",
            field=models.FileField(
                upload_to="activities/files/",
                validators=[
                    config.validators.FileSizeValidator(20),
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx", "ppt", "pptx", "mp4", "mp3", "wav"]
                    ),
                ],
                verbose_name="الملف",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="news/files/",
                validators=[
                    config.validators.FileSizeValidator(20),
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx", "ppt", "pptx", "mp4", "mp3", "wav"]
                    ),
                ],
                verbose_name="مرفق",
            ),
        ),
    ]
