# Generated by Django 5.1.15 on 2026-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_activityfile_file_alter_news_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="اليوم")),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الزيارات"),
                ),
            ],
            options={
                "verbose_name": "زيارات يوم",
                "verbose_name_plural": "إحصاء الزيارات",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_view_counts",
            field=models.BooleanField(
                default=False, verbose_name="إظهار عدد المشاهدات للجميع"
            ),
        ),
    ]
